---
- hosts: vagrant
  vars:
    scala_version: 2.10.3
    sbt_version: 0.13.0
  user: vagrant
  sudo: yes
  tasks:
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400

    - name: Update all packages
      apt: upgrade=dist

   ###########################################################################################################################################
   # For ORACLE JAVA 7:
   # These steps are required to get the Oracle version of Java installed.  If you want OpenJDK instead, comment out these tasks and uncomment
   # the one in the OpenJDK section
   ###########################################################################################################################################
    - name: Install PyCurl (required for apt-repository updates)
      apt: pkg=python-pycurl

    - name: Install Oracle Java Repo Installer Repository
      apt_repository: repo=ppa:webupd8team/java update-cache=yes

    - name: Wizardry to bypass the Oracle License File prompt
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

    - name: Install Oracle Java 7
      apt: pkg=oracle-java7-installer
    ##########################################################################################################################################
    # For OpenJDK:
    ##########################################################################################################################################
    # - name: Install OpenJDK 7
    #   apt: pkg=openjdk-7-jdk
    ##########################################################################################################################################

    - name: Create Ansible Cache Directory
      file: path=/var/local/ansible-cache state=directory

    - name: Download Scala {{scala_version}}
      get_url: dest=/var/local/ansible-cache/ url=http://www.scala-lang.org/files/archive/scala-{{scala_version}}.tgz

    - name: Extract Scala
      shell: tar xzf /var/local/ansible-cache/scala-{{scala_version}}.tgz -C /usr/local/share creates=/usr/local/share/scala-{{scala_version}}

    - name: Add Scala executable symlinks to path
      shell: for f in fsc scala scalac scaladoc scalap; do ln -s /usr/local/share/scala-{{scala_version}}/bin/$f /usr/local/bin/$f; done; creates=/usr/local/bin/scala

    - name: Download SBT {{sbt_version}}
      get_url: dest=/var/local/ansible-cache url=https://dl.bintray.com/sbt/native-packages/sbt/{{sbt_version}}/sbt-{{sbt_version}}.tgz

    - name: Extract SBT {{sbt_version}}
      shell: tar xzf /var/local/ansible-cache/sbt-{{sbt_version}}.tgz -C /usr/local/share creates=/usr/local/share/sbt

    - name: Add SBT executable symlinks to path
      shell: for f in sbt sbt-launch.jar; do ln -s /usr/local/share/sbt/bin/$f /usr/local/bin/$f; done; creates=/usr/local/bin/sbt

    - name: Update Scala environment variables
      sudo: no
      lineinfile: line="export SCALA_HOME=/usr/local/share/scala" dest="~/.bashrc" state=present regexp="export SCALA_HOME=/usr/local/share/scala"
